postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    repository: docker.io/dustinvanbuskirk/result
    tag: 99f5e1c
vote:
  image:
    repository: docker.io/dustinvanbuskirk/vote
    tag: 99f5e1c
worker:
  image:
    repository: docker.io/dustinvanbuskirk/worker
    tag: d222228
